Response invalid fix/Limit returned movies
josephschmitt/alexa-couchpotato pull request #4
Opened 2016-10-27 11:47 UTC by sharepointalex

Rebuild new array of returned movies with minimum required movie data to
fix response invalid on Echo devices (due to response size limitation).

Also used node-couchpotato to limit the returned number of movies to 5 as opposed to slicing the array.

2016-10-27 22:27 UTC, josephschmitt reviewed
Nitpicky styling stuff otherwise ship it!

2016-10-27 22:27 UTC, josephschmitt commented on lib/handlers.js
> +  debug:true
Do we want to leave debug on? What does it do?

2016-10-27 22:27 UTC, josephschmitt commented on lib/utils.js
> +{
Sorry to be picky, but do you mind updating all these open curlies to be on the same line as the function? Just want the formatting to internally consistent in this file.

2016-10-28 07:44 UTC, alexc-MSFT commented on lib/handlers.js
> +  debug:true
Returns some more info in the response - might be worth it whilst continuing to dev - shouldnt effect people using it.

2016-10-28 07:45 UTC, sharepointalex commented on lib/utils.js
> +{
Done after a ton of commits - I think

2016-10-28 16:41 UTC, hackworth requested changes

2016-10-28 16:41 UTC, Hackworth commented on lib/handlers.js
Duplicate return false

2016-10-28 16:41 UTC, Hackworth commented on lib/utils.js
> +          inLibrary: isInLibrary(movies[i].in_library),
in_library not inLibrary

2016-10-28 16:41 UTC, Hackworth commented on lib/handlers.js
> +   utils.sendSearchResponse(movies, movieName, resp);
Sending movieName?

2016-10-28 19:22 UTC, sharepointalex commented on lib/utils.js
> +          inLibrary: isInLibrary(movies[i].in_library),
I added a new function to check if the movie is already in your library (different json is defined) but I didn't commit that function - removed the reference to it.

2016-10-28 19:22 UTC, sharepointalex commented on lib/handlers.js
> +   utils.sendSearchResponse(movies, movieName, resp);
That's because in sendSearchResponse it looks for movieName which was not being passed in

2016-10-28 19:22 UTC, sharepointalex commented on lib/handlers.js
Fixed - ta

2016-10-28 19:29 UTC, sharepointalex commented
Clearly I need to get better at Git (sorry i'm new to it) - made a ton of commits but I think I got there in the end!

2016-10-29 03:30 UTC, josephschmitt commented
@sharepointalex @Hackworth this is awesome, you guys rock.

2016-10-29 03:30 UTC, merged